# 2. Matrix Multiplication in PyTorch

Matrix multiplication is essential for neural networks!
PyTorch provides efficient operations for multiplying matrices and tensors.


In [1]:
import torch


## 1. Matrix Multiplication (@ operator)

Use the @ operator or torch.matmul() for matrix multiplication!
A @ B multiplies matrices A and B.


In [2]:
# Create two matrices
A = torch.tensor([[1, 2], 
                  [3, 4]], dtype=torch.float32)

B = torch.tensor([[5, 6], 
                  [7, 8]], dtype=torch.float32)

print("Matrix A:")
print(A)
print(f"Shape: {A.shape}")
print()

print("Matrix B:")
print(B)
print(f"Shape: {B.shape}")
print()

# Matrix multiplication using @
result = A @ B
print("A @ B (matrix multiplication):")
print(result)
print(f"Shape: {result.shape}")
print()

# Using torch.matmul()
result2 = torch.matmul(A, B)
print("torch.matmul(A, B):")
print(result2)
print("(Same result!)")


Matrix A:
tensor([[1., 2.],
        [3., 4.]])
Shape: torch.Size([2, 2])

Matrix B:
tensor([[5., 6.],
        [7., 8.]])
Shape: torch.Size([2, 2])

A @ B (matrix multiplication):
tensor([[19., 22.],
        [43., 50.]])
Shape: torch.Size([2, 2])

torch.matmul(A, B):
tensor([[19., 22.],
        [43., 50.]])
(Same result!)


## 2. Matrix-Vector Multiplication

Multiply a matrix by a vector to transform it!


In [3]:
# Matrix-vector multiplication
M = torch.tensor([[1, 2], 
                  [3, 4]], dtype=torch.float32)

v = torch.tensor([5, 6], dtype=torch.float32)

print("Matrix M:")
print(M)
print(f"Shape: {M.shape}")
print()

print("Vector v:")
print(v)
print(f"Shape: {v.shape}")
print()

# Matrix × Vector
result = M @ v
print("M @ v (matrix-vector multiplication):")
print(result)
print(f"Shape: {result.shape}")
print()

# How it works
print("How it works:")
print(f"Result[0] = M[0, 0]*v[0] + M[0, 1]*v[1] = {M[0, 0]}*{v[0]} + {M[0, 1]}*{v[1]} = {result[0]}")
print(f"Result[1] = M[1, 0]*v[0] + M[1, 1]*v[1] = {M[1, 0]}*{v[0]} + {M[1, 1]}*{v[1]} = {result[1]}")


Matrix M:
tensor([[1., 2.],
        [3., 4.]])
Shape: torch.Size([2, 2])

Vector v:
tensor([5., 6.])
Shape: torch.Size([2])

M @ v (matrix-vector multiplication):
tensor([17., 39.])
Shape: torch.Size([2])

How it works:
Result[0] = M[0, 0]*v[0] + M[0, 1]*v[1] = 1.0*5.0 + 2.0*6.0 = 17.0
Result[1] = M[1, 0]*v[0] + M[1, 1]*v[1] = 3.0*5.0 + 4.0*6.0 = 39.0


## 3. Batch Matrix Multiplication

Process multiple matrices at once using batch dimensions!
Very useful for neural networks!


In [4]:
# Batch matrix multiplication
# Create batch of matrices: (batch_size, rows, cols)
batch_A = torch.randn(3, 2, 4)  # 3 matrices, each 2×4
batch_B = torch.randn(3, 4, 3)  # 3 matrices, each 4×3

print("Batch A (3 matrices, each 2×4):")
print(batch_A)
print(f"Shape: {batch_A.shape}")
print()

print("Batch B (3 matrices, each 4×3):")
print(batch_B)
print(f"Shape: {batch_B.shape}")
print()

# Batch matrix multiplication
batch_result = torch.bmm(batch_A, batch_B)
print("Batch matrix multiplication result:")
print(batch_result)
print(f"Shape: {batch_result.shape}")
print("(3 matrices, each 2×3)")
print()

# Verify: first matrix multiplication
A0 = batch_A[0]
B0 = batch_B[0]
result0 = A0 @ B0

print("First matrix multiplication (manual):")
print(result0)
print()

print("First matrix multiplication (from batch):")
print(batch_result[0])
print("(Should match!)")
print(f"Are they equal? {torch.allclose(result0, batch_result[0])}")


Batch A (3 matrices, each 2×4):
tensor([[[ 0.2265,  0.9571, -2.5396,  0.7601],
         [-0.4338, -0.3959, -1.0891, -0.6893]],

        [[-0.8776,  1.9484, -0.4687,  0.3557],
         [ 0.5360,  0.5965, -1.1943, -1.1391]],

        [[ 1.5603, -0.8267,  0.1713,  1.7305],
         [-1.3028,  0.1968, -2.1413, -0.3610]]])
Shape: torch.Size([3, 2, 4])

Batch B (3 matrices, each 4×3):
tensor([[[-0.0429, -1.6334, -1.9289],
         [-0.0808,  1.0259,  0.0299],
         [ 0.1528, -1.1578, -0.9339],
         [-1.1520, -0.7758,  1.4245]],

        [[-0.0998,  0.9886,  0.9391],
         [-0.1247, -0.5991, -1.0661],
         [-0.2951, -1.0657,  0.1303],
         [-1.1359, -0.2168,  1.1947]],

        [[-0.3951,  1.6309, -0.3291],
         [-0.6573, -0.3659,  0.7526],
         [ 0.8745, -0.1428,  0.3937],
         [ 0.4675,  1.6015, -0.9353]]])
Shape: torch.Size([3, 4, 3])

Batch matrix multiplication result:
tensor([[[-1.3506,  2.9627,  3.0464],
         [ 0.6782,  2.0982,  0.8603]],

        [[-0